theme = "tokyonight"

[editor]
idle-timeout = 200
line-number = "relative" # Números relativos facilitam saltos (ex: 10j)
cursorline = true        # Destaca a linha onde você está
color-modes = true       # Muda a cor da barra de status conforme o modo (Normal, Insert, etc)
bufferline = "always"    # Mostra as abas no topo como em navegadores

[editor.cursor-shape]
insert = "bar"      # Estilo VS Code no modo de inserção
normal = "block"    # Bloco clássico no modo normal
select = "underline" # Sublinhado para seleções

[editor.indent-guides]
render = true       # Linhas verticais para guiar a indentação
character = "╎"     # Caractere discreto e elegante
skip-levels = 1     # Não mostra a primeira linha na margem esquerda

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"

[editor.lsp]
display-inlay-hints = true # Mostra tipos de variáveis e parâmetros inline
display-messages = true    # Mostra o que o LSP está fazendo no rodapé
# Aumenta o tempo de espera para 60 segundos
