# --- GOLANG ---
[[language]]
name = "go"
roots = ["go.mod"]
auto-format = true

# --- TYPESCRIPT / JAVASCRIPT ---
[[language]]
name = "typescript"
roots = ["package.json", "tsconfig.json"]
auto-format = true
indent = { tab-width = 2, unit = " " }

# --- SVELTE ---
[[language]]
name = "svelte"
roots = ["svelte.config.js", "package.json"]
auto-format = true
indent = { tab-width = 2, unit = " " }
