gui:
  theme:
    activeBorderColor:
      - "#fabd2f" # Gruvbox Yellow (Foco principal)
      - bold
    inactiveBorderColor:
      - "#504945" # Gruvbox Gray (Borda inativa discreta)
    optionsTextColor:
      - "#83a598" # Gruvbox Blue (Atalhos)
    selectedLineBgColor:
      - "#3c3836" # Fundo da linha selecionada (Cinza suave)
    selectedRangeBgColor:
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#b8bb26" # Gruvbox Green
    cherryPickedCommitFgColor:
      - "#282828" # Contraste escuro
    unstagedChangesColor:
      - "#fb4934" # Gruvbox Red (Para arquivos modificados/não stageados)
    defaultFgColor:
      - "#ebdbb2" # Cream (Cor do texto padrão)
    searchingActiveBorderColor:
      - "#fe8019" # Gruvbox Orange (Quando estiver buscando algo)
