"$schema" = 'https://starship.rs/config-schema.json'
palette = 'tokyonight_storm'

format = """
[](fg:surface2)\
$os$username\
[](fg:surface2)\
$directory\
[](fg:bg2 bg:blue)\
$c$rust$nodejs$python$golang$docker_context\
[](fg:blue bg:bg)\
$line_break$character
"""

[palettes.tokyonight_storm]
bg = "#1a1b26"
bg2= "#24283b"
fg = "#c0caf5"
text = "#c0caf5"
base = "#1a1b26"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
pink = "#f7768e"
purple = "#9d7cd8"
red = "#f7768e"
teal = "#1abc9c"
yellow = "#e0af68"
comment = "#565f89"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
mantle = "#1e2030"

[os]
disabled = false
style = "bg:surface0 fg:text"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:text bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:mantle bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:mantle bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'

[golang]
symbol = ""
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'


[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:mantle bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:mantle bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:purple fg:mantle"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
