# Visual theme: Tokyonight

### Tokyo Night Theme configuration
set -g @tokyo-night-tmux_theme storm    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 0  # 1 or 0

# Numbers syles
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

# Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0

# module support in mint
set -g @tokyonight_status_modules 'datetime battery cpu'

# Mode copy (search, section, etc.)
set -g mode-style "fg=#c0caf5,bg=#1a1b26"       # Text light blue in dark backgroud
set -g message-style "fg=#7aa2f7,bg=#1a1b26" 
set -g message-command-style "fg=#7dcfff,bg=#1a1b26"
